version: '3'
services:

  rabbit:
    image: rabbitmq:3.12.4-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always

  db:
    image: mongo:7.0.0
    container_name: db
    ports:
     - "27017:27017"
    restart: always
  
  gateway:
    image: gateway
    build: 
      context: ./services/gateway
      dockerfile: Dockerfile-prod
    container_name: gateway
    ports:
      - "4000:80"
    environment:
      - PORT=80
    depends_on:
      - history
      - metadata
      - video-streaming
      - video-uploader
    restart: "no"
  
  videos-storage:
    image: videos-storage
    build: 
      context: ./services/videos-storage
      dockerfile: Dockerfile-prod
    container_name: videos-storage
    ports:
     - "4001:80"
    environment:
      - PORT=80
      - STORAGE_BUCKET_NAME=${STORAGE_BUCKET_NAME}
      - STORAGE_REGION_NAME=${STORAGE_REGION_NAME}
      - STORAGE_ACCESS_KEY_ID=${STORAGE_ACCESS_KEY_ID}
      - STORAGE_SECRET_ACCESS_KEY=${STORAGE_SECRET_ACCESS_KEY}
    restart: "no"

  history:
    image: history
    build: 
      context: ./services/history
      dockerfile: Dockerfile-prod
    container_name: history
    ports:
     - "4002:80"
    environment:
      - PORT=80
      - RABBIT=amqp://guest:guest@rabbit:5672
      - DBHOST=mongodb://db:27017
      - DBNAME=history
    depends_on:
      db:
        condition: service_started
      rabbit:
        condition: service_healthy
    restart: "no"
  
  recommendations:
    image: recommendations
    build: 
      context: ./services/recommendations
      dockerfile: Dockerfile-prod
    container_name: recommendations
    ports:
     - "4003:80"
    environment:
      - PORT=80
      - RABBIT=amqp://guest:guest@rabbit:5672
      - DBHOST=mongodb://db:27017
      - DBNAME=recommendations
    depends_on:
      db:
        condition: service_started
      rabbit:
        condition: service_healthy
    restart: "no"
  
  metadata:
    image: metadata
    build: 
      context: ./services/metadata
      dockerfile: Dockerfile-prod
    container_name: metadata
    ports:
     - "4004:80"
    environment:
      - PORT=80
      - RABBIT=amqp://guest:guest@rabbit:5672
      - DBHOST=mongodb://db:27017
      - DBNAME=metadata
    depends_on:
      db:
        condition: service_started
      rabbit:
        condition: service_healthy
    restart: "no"
  
  video-uploader:
    image: video-uploader
    build: 
      context: ./services/video-uploader
      dockerfile: Dockerfile-prod
    container_name: video-uploader
    ports:
     - "4005:80"
    environment:
      - PORT=80
      - RABBIT=amqp://guest:guest@rabbit:5672
    depends_on:
      rabbit:
        condition: service_healthy
      videos-storage:
        condition: service_healthy
    restart: "no"
  
  video-streaming:
    image: video-streaming
    build: 
      context: ./services/video-streaming
      dockerfile: Dockerfile-prod
    container_name: video-streaming
    ports:
     - "4006:80"
    environment:
      - PORT=80
      - RABBIT=amqp://guest:guest@rabbit:5672
    depends_on:
      rabbit:
        condition: service_healthy
      videos-storage:
        condition: service_healthy
    restart: "no"