openapi: 3.0.3
info:
  title: Video Streaming Service API
  description: Service for streaming videos and tracking views
  version: "1.0.0"
paths:
  /api/live:
    get:
      summary: Health check endpoint
      description: Used to verify the service is running
      responses:
        "200":
          description: Service is healthy

  /api/v1/video:
    get:
      summary: Stream a video
      description: Streams a video by ID and broadcasts a 'viewed' message
      parameters:
        - name: id
          in: query
          description: ID of the video to stream
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Video file stream
          content:
            video/*:
              schema:
                type: string
                format: binary
        "500":
          description: Error occurred while streaming the video
          content:
            text/plain:
              schema:
                type: string
