openapi: 3.0.3
info:
  title: API Gateway Service
  description: Gateway service that routes requests to appropriate microservices
  version: "1.0.0"
paths:
  /api/live:
    get:
      summary: Health check endpoint
      description: Used to verify the service is running
      responses:
        "200":
          description: Service is healthy

  /api/v1/videos/upload:
    post:
      summary: Upload a video
      description: Upload a video file to the system
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                video:
                  type: string
                  format: binary
                  description: The video file to upload
                fileName:
                  type: string
                  description: Name of the video file
      responses:
        "200":
          description: Video uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The ID assigned to the uploaded video
        "500":
          description: Error occurred while uploading the video
          content:
            text/plain:
              schema:
                type: string

  /api/v1/videos/stream:
    get:
      summary: Stream a video
      description: Stream a video file by ID
      parameters:
        - name: id
          in: query
          description: ID of the video to stream
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Video file stream
          content:
            video/mp4:
              schema:
                type: string
                format: binary
        "404":
          description: Video not found
        "500":
          description: Error occurred while streaming the video
