apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: flixtube
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers: 
      - name: gateway
        image: crazydanila/gateway:df54efa99990154a7956c317554fdd74fffcaba1
        imagePullPolicy: IfNotPresent
        ports:
        - name: gateway-port
          containerPort: 4000
        env:
        - name: PORT
          value: "4000"
        readinessProbe:
          httpGet:
            path: /api/live
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  namespace: flixtube
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000