apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: flixtube
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers: 
      - name: gateway
        image: crazydanila/gateway:e642902dfb94b326095d40d103fd9ea1369dd739
        imagePullPolicy: IfNotPresent
        ports:
        - name: gateway-port
          containerPort: 4000
        env:
        - name: PORT
          value: "4000"
---
apiVersion: v1
kind: Service
metadata:
  namespace: flixtube
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000