apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: flixtube
  name: history
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history
  template:
    metadata:
      labels:
        app: history
    spec:
      containers: 
      - name: history
        image: crazydanila/history:af367a45b984e730bda2fa215f5330f9182e6c30
        imagePullPolicy: IfNotPresent
        ports:
        - name: history-port
          containerPort: 4002
        env:
        - name: PORT
          value: "4002"
        - name: RABBIT
          value: "amqp://guest:guest@rabbit:5672"
        - name: DBHOST
          value: "mongodb://db:27017"
        - name: DBNAME
          value: "history"
        resources:
          limits:
            cpu: "1.0"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /api/live
            port: 4002
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  namespace: flixtube
  name: history
spec:
  selector:
    app: history
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4002