apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: flixtube
  name: metadata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata
  template:
    metadata:
      labels:
        app: metadata
    spec:
      containers: 
      - name: metadata
        image: crazydanila/metadata:a783ed6f84d79caee8e5782b9e9f06e6b7e22853
        imagePullPolicy: IfNotPresent
        ports:
        - name: metadata-port
          containerPort: 4004
        env:
        - name: PORT
          value: "4004"
        - name: RABBIT
          value: "amqp://guest:guest@rabbit:5672"
        - name: DBHOST
          value: "mongodb://db:27017"
        - name: DBNAME
          value: "metadata"
        readinessProbe:
          httpGet:
            path: /api/live
            port: 4004
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  namespace: flixtube
  name: metadata
spec:
  selector:
    app: metadata
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4004