apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: flixtube
  name: videos-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: videos-storage
  template:
    metadata:
      labels:
        app: videos-storage
    spec:
      containers: 
      - name: videos-storage
        image: crazydanila/videos-storage:5686ea3c005ab3d058e8994e03efdfad3c4fbbe9
        imagePullPolicy: IfNotPresent
        ports:
        - name: storage-port
          containerPort: 4001
        env:
        - name: PORT
          value: "4001"
        - name: STORAGE_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: videos-storage-config
              key: STORAGE_BUCKET_NAME
        - name: STORAGE_REGION_NAME
          valueFrom:
            configMapKeyRef:
              name: videos-storage-config
              key: STORAGE_REGION_NAME
        - name: STORAGE_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-keys
              key: STORAGE_ACCESS_KEY_ID
        - name: STORAGE_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-keys
              key: STORAGE_SECRET_ACCESS_KEY
        resources:
          limits:
            cpu: "1.0"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /api/live
            port: 4001
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  namespace: flixtube
  name: videos-storage
spec:
  selector:
    app: videos-storage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4001