apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: flixtube
  name: video-uploader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-uploader
  template:
    metadata:
      labels:
        app: video-uploader
    spec:
      containers: 
      - name: video-uploader
        image: crazydanila/video-uploader:a783ed6f84d79caee8e5782b9e9f06e6b7e22853
        imagePullPolicy: IfNotPresent
        ports:
        - name: uploader-port
          containerPort: 4005
        env:
        - name: PORT
          value: "4005"
        - name: RABBIT
          value: "amqp://guest:guest@rabbit:5672"
        readinessProbe:
          httpGet:
            path: /api/live
            port: 4005
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  namespace: flixtube
  name: video-uploader
spec:
  selector:
    app: video-uploader
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4005