apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: flixtube
  name: rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers: 
      - name: rabbit
        image: rabbitmq:3.12.4-management
        imagePullPolicy: IfNotPresent
        ports:
        - name: rabbit-port
          containerPort: 5672
        - name: rabbit-ui-port
          containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  namespace: flixtube
  name: rabbit
spec:
  selector:
    app: rabbit
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
      name: rabbit-port
    - protocol: TCP
      port: 15672
      targetPort: 15672
      name: rabbit-ui-port