apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: flixtube
  name: recommendations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendations
  template:
    metadata:
      labels:
        app: recommendations
    spec:
      containers: 
      - name: recommendations
        image: crazydanila/recommendations:1
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "4003"
        - name: RABBIT
          value: "amqp://guest:guest@rabbit:5672"
        - name: DBHOST
          value: "mongodb://db:27017"
        - name: DBNAME
          value: "recommendations"
---
apiVersion: v1
kind: Service
metadata:
  namespace: flixtube
  name: recommendations
spec:
  selector:
    app: recommendations
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4003