apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: flixtube
  name: video-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-streaming
  template:
    metadata:
      labels:
        app: video-streaming
    spec:
      containers: 
      - name: video-streaming
        image: video-streaming:1
        imagePullPolicy: Never
        ports:
        - name: streaming-port
          containerPort: 4000
        env:
        - name: PORT
          value: "4000"
        - name: RABBIT
          value: "amqp://guest:guest@rabbit:5672"
        - name: DBHOST
          value: "mongodb://db:27017"
        - name: DBNAME
          value: "video-streaming"
        - name: VIDEO_STORAGE_HOST
          value: "video-storage"
        - name: VIDEO_STORAGE_PORT
          value: "80"
---
apiVersion: v1
kind: Service
metadata:
  namespace: flixtube
  name: video-streaming
spec:
  selector:
    app: video-streaming
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
      nodePort: 30000