name: Deploy service

on:
  #
  # Allows deployment to be invoked manually through the GitHub Actions user interface.
  #
  workflow_dispatch:
    inputs:
      service:
        description: 'Service to deploy'     
        required: true

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}

    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3

      #
      # Builds the Docker image.
      #
      - name: Build
        run: ./deploy/build-image.sh ${{ github.event.inputs.service }}
    
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_UN }}
          password: ${{ secrets.REGISTRY_PW  }}

      #
      # Publishes the Docker image to the container registry.
      #
      - name: Publish
        run: ./deploy/push-image.sh ${{ github.event.inputs.service }}