name: "Continuous Integration: gateway"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] 

defaults:
  run:
    working-directory: services/gateway
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: services/gateway/package-lock.json
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Build service
      run: npm run build --if-present

    - name: Run Unit Tests
      run: npm test